#include <stdio.h>
#define VK_USE_PLATFORM_WAYLAND_KHR
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#define GLFW_EXPOSE_NATIVE_WAYLAND
#include <GLFW/glfw3native.h>

#include <vulkan/vulkan.h>
#include <vulkan/vulkan_core.h>
#include <math.h>

#include "headers/vulkan_misc.h"
#include "headers/datatypes.h"
#include "headers/window.h"
#include "headers/misc.h"

// TODO: replace xxd with script in build.c
#include "../tmp/test.pv.h" // Auto generated by xxd

static void error_callback(int error, const char* description) {
    fprintf(stderr, "[GLFW Error]: %s\n\n", description);
}

void init_glfw(Program* program) {
    try(glfwInit(), "Couldn't initialise glfw");
    glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API); // disable opengl

#ifdef DEBUG // setup debugger
    glfwSetErrorCallback(error_callback);
#endif

    try_c(glfwVulkanSupported(), "Vulkan is not supported by glfw", glfwTerminate);

    program->window = glfwCreateWindow(800, 600, "Vulkan engine", NULL, NULL);
    try_c(program->window, "Couldn't create glfw window", glfwTerminate);

    chk(glfwCreateWindowSurface(program->instance, program->window, NULL, &program->surface));
    create_swapchain(program);
}

void transition_image(Program* program, VkImage src_image, VkImageLayout old_layout, VkImageLayout new_layout) {
    VkImageSubresourceRange range = {
        .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
        .baseMipLevel = 0,
        .baseArrayLayer = 0,
        .layerCount = 1,
        .levelCount = 1
    };

    VkImageMemoryBarrier2 image_barrier = {
        .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2,
        .srcStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT,
        .srcAccessMask = VK_ACCESS_2_MEMORY_WRITE_BIT,
        .dstStageMask = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT,
        .dstAccessMask = VK_ACCESS_2_MEMORY_WRITE_BIT | VK_ACCESS_2_MEMORY_READ_BIT,
        .oldLayout = old_layout,
        .newLayout = new_layout,
        .srcQueueFamilyIndex = program->queue_family_index,
        .dstQueueFamilyIndex = program->queue_family_index,
        .image = src_image,
        .subresourceRange = range,
    };

    VkDependencyInfo dependency_info = {
        .sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO,
        .imageMemoryBarrierCount = 1,
        .pImageMemoryBarriers = &image_barrier,
    };

    vkCmdPipelineBarrier2(program->cmd_buffer, &dependency_info);
}

void create_descriptor_set(
    VkDevice device,
    DescriptorBindingLayout* layout, // Bindings vector: bindings per set
    VkDescriptorSet* descriptor_set,
    VkDescriptorPool* descriptor_pool, // useless outside, but descriptor_set lifetime is tied to it
    VkDescriptorSetLayout* out_layout
) {
    VkDescriptorSetLayoutBinding* bindings = NULL;
    VkDescriptorBindingFlags* flags = NULL;
    VkDescriptorPoolSize* pool_sizes = NULL;
    u32* descriptor_counts = NULL;

    // Preallocate the vector
    vec_sized(bindings, vec_len(layout));
    vec_sized(flags, vec_len(layout));
    vec_sized(pool_sizes, vec_len(layout));
    vec_sized(descriptor_counts, vec_len(layout));

    for (size_t binding_i = 0; binding_i < vec_len(layout); ++binding_i) {
        vec_push(flags, layout[binding_i].flags);

        VkDescriptorSetLayoutBinding descriptor_layout_binding = {
            .descriptorType = layout[binding_i].type,
            .descriptorCount = layout[binding_i].descriptor_count,
            .stageFlags = VK_SHADER_STAGE_COMPUTE_BIT,
            .binding = layout[binding_i].binding,
        };
        vec_push(bindings, descriptor_layout_binding);

        VkDescriptorPoolSize pool_size = {
            .type = layout[binding_i].type,
            .descriptorCount = layout[binding_i].descriptor_count,
        };
        vec_push(pool_sizes, pool_size);

        vec_push(descriptor_counts, layout[binding_i].descriptor_count);
    }

    VkDescriptorSetLayoutBindingFlagsCreateInfo descriptor_binding_flags = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO,
        .bindingCount = vec_len(flags),
        .pBindingFlags = flags,
    };

    VkDescriptorSetLayoutCreateInfo layout_create_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .pNext = &descriptor_binding_flags,
        .bindingCount = vec_len(bindings),
        .pBindings = bindings,
    };

    chk(vkCreateDescriptorSetLayout(device, &layout_create_info, NULL, out_layout));

    VkDescriptorPoolCreateInfo descriptor_pool_create_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
        .maxSets = 1, // I will leave it as 1 for now because I don't undestand
        .poolSizeCount = vec_len(pool_sizes),
        .pPoolSizes = pool_sizes,
    };

    chk(vkCreateDescriptorPool(device, &descriptor_pool_create_info, NULL, descriptor_pool));

    VkDescriptorSetVariableDescriptorCountAllocateInfo count_allocate_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO,
        .descriptorSetCount = vec_len(descriptor_counts),
        .pDescriptorCounts = descriptor_counts,
    };

    VkDescriptorSetAllocateInfo descriptor_allocate_info = {
        .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
        .pNext = &count_allocate_info,
        .descriptorPool = *descriptor_pool,
        .descriptorSetCount = 1, // Same with maxSets, I don't understand
        .pSetLayouts = out_layout,
    };

    chk(vkAllocateDescriptorSets(device, &descriptor_allocate_info, descriptor_set));

    vec_free(flags);
    vec_free(bindings);
    vec_free(pool_sizes);
    vec_free(descriptor_counts);
}

// TODO: replace this function with a dynamic content-aware loop header
void window_code(Program* program) {
    PFN_vkCmdClearColorImage vkCmdClearColorImage =
        (PFN_vkCmdClearColorImage)
        vkGetInstanceProcAddr(program->instance, "vkCmdClearColorImage");
    assert(vkCmdClearColorImage != NULL &&
        "[FATAL ERROR] Couldn't vkCmdClearColorImage method");

    VkShaderModuleCreateInfo shader_create_info = {
        .sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = tmp_test_spv_len,
        .pCode = (u32*)tmp_test_spv
    };

    VkShaderModule shader;
    chk(vkCreateShaderModule(program->device, &shader_create_info, NULL, &shader));

    VkPipelineShaderStageCreateInfo stage_create_info = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
        .stage = VK_SHADER_STAGE_COMPUTE_BIT,
        .module = shader,
        .pName = "main",
    };

    VkDescriptorSet descriptor_set;
    VkDescriptorPool descriptor_pool;
    VkDescriptorSetLayout descriptor_set_layout;
    DescriptorBindingLayout binding_layout1 = {
        .binding = 1,
        .descriptor_count = 1,
        .flags = VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT,
        .type = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
    };

    create_descriptor_set(program->device, new_vec(DescriptorBindingLayout, binding_layout1), &descriptor_set, &descriptor_pool, &descriptor_set_layout);

    VkPipelineLayoutCreateInfo pipeline_layout_create_info = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .setLayoutCount = 1,
        .pSetLayouts = &descriptor_set_layout,
        .pushConstantRangeCount = 0,
        .pPushConstantRanges = NULL,
    };

    VkPipelineLayout pipeline_layout;
    chk(vkCreatePipelineLayout(program->device, &pipeline_layout_create_info, NULL, &pipeline_layout));

    VkComputePipelineCreateInfo pipeline_create_info = {
        .sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO,
        .layout = pipeline_layout,
        .stage = stage_create_info,
        .basePipelineHandle = VK_NULL_HANDLE,
        .basePipelineIndex = -1,
    };

    VkPipeline compute_pipeline;
    chk(vkCreateComputePipelines(program->device, VK_NULL_HANDLE, 1, &pipeline_create_info, NULL, &compute_pipeline));

    // VkWriteDescriptorSet* descriptor_set_writes = NULL;
    // vec_sized(descriptor_set_writes, 1); // preallocate the vector, usefull when more than 1 descriptor set
    VkWriteDescriptorSet descriptor_set_writes[1];

    while (!glfwWindowShouldClose(program->window)) {
        double time = glfwGetTime();
        try(time, "Couldn't get glfw time.");

        vkWaitForFences(program->device, 1, &program->frame_fence, VK_TRUE, UINT64_MAX);
        vkResetFences(program->device, 1, &program->frame_fence);

        u32 image_index = UINT32_MAX;
        VkResult res = vkAcquireNextImageKHR(
            program->device,
            program->swapchain,
            UINT32_MAX,
            program->image_aviable,
            VK_NULL_HANDLE,
            &image_index
        );

        if (res == VK_ERROR_OUT_OF_DATE_KHR) {
            create_swapchain(program);
            continue;
        } else chk(res);
        try(image_index < vec_len(program->images), "Failed to get image from swapchain");

        vkResetCommandBuffer(program->cmd_buffer, 0);
        VkCommandBufferBeginInfo begin_info = { .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO };
        vkBeginCommandBuffer(program->cmd_buffer, &begin_info);

        // VkImageSubresourceRange range = {
        //     .aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
        //     .baseMipLevel = 0,
        //     .baseArrayLayer = 0,
        //     .layerCount = 1,
        //     .levelCount = 1
        // };

        // Actual drawing here
        // VkClearColorValue color = {(float)sin(time) / 2.0 + .5, .5, 1, 1};

        transition_image(program, program->images[image_index], VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL);
        // vkCmdClearColorImage(
        //     program->cmd_buffer,
        //     program->images[image_index],
        //     VK_IMAGE_LAYOUT_GENERAL,
        //     &color, 1, &range
        // );

        VkImageViewCreateInfo image_view_create_info = {
            .sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
            .image = program->images[image_index],
            .viewType = VK_IMAGE_VIEW_TYPE_2D,
            .format = IMAGE_FORMAT,
            .components.r = VK_COMPONENT_SWIZZLE_IDENTITY,
            .components.g = VK_COMPONENT_SWIZZLE_IDENTITY,
            .components.b = VK_COMPONENT_SWIZZLE_IDENTITY,
            .components.a = VK_COMPONENT_SWIZZLE_IDENTITY,
            .subresourceRange.aspectMask = VK_IMAGE_ASPECT_COLOR_BIT,
            .subresourceRange.baseMipLevel = 0,
            .subresourceRange.baseArrayLayer = 0,
            .subresourceRange.layerCount = 1,
            .subresourceRange.levelCount = 1,
        };

        VkImageView image_view;
        chk(vkCreateImageView(program->device, &image_view_create_info, NULL, &image_view));

        VkDescriptorImageInfo out_img = {
            .imageView = image_view,
            .imageLayout = VK_IMAGE_LAYOUT_GENERAL,
        };

        descriptor_set_writes[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        descriptor_set_writes[0].dstSet = descriptor_set;
        descriptor_set_writes[0].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
        descriptor_set_writes[0].dstBinding = 1;
        descriptor_set_writes[0].dstArrayElement = 0;
        descriptor_set_writes[0].descriptorCount = 1;
        descriptor_set_writes[0].pImageInfo = &out_img;

        vkUpdateDescriptorSets(program->device, 1, descriptor_set_writes, 0, NULL);

        vkCmdBindPipeline(program->cmd_buffer, VK_PIPELINE_BIND_POINT_COMPUTE, compute_pipeline);
        vkCmdBindDescriptorSets(program->cmd_buffer, VK_PIPELINE_BIND_POINT_COMPUTE, pipeline_layout, 0, 1, &descriptor_set, 0, NULL);

        vkCmdDispatch(program->cmd_buffer, 16, 16, 1);

        transition_image(program, program->images[image_index], VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_PRESENT_SRC_KHR);
        vkEndCommandBuffer(program->cmd_buffer);

        vkDestroyImageView(program->device, image_view, NULL);

        VkPipelineStageFlags wait_stages[] = {
            VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT
        };

        VkSubmitInfo submit_info = {
            .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
            .waitSemaphoreCount = 1,
            .pWaitSemaphores = &program->image_aviable,
            .pWaitDstStageMask = wait_stages,
            .commandBufferCount = 1,
            .pCommandBuffers = &program->cmd_buffer,
            .signalSemaphoreCount = 1,
            .pSignalSemaphores = program->submit_semaphores + image_index,
        };

        chk(vkQueueSubmit(program->queue, 1, &submit_info, program->frame_fence));

        VkPresentInfoKHR present_info = {
            .sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR,
            .waitSemaphoreCount = 1,
            .pWaitSemaphores = program->submit_semaphores + image_index,
            .swapchainCount = 1,
            .pSwapchains = &program->swapchain,
            .pImageIndices = &image_index,
        };

        VkResult res2 = vkQueuePresentKHR(program->queue, &present_info);
        if (res == VK_ERROR_OUT_OF_DATE_KHR) {
            create_swapchain(program);
            continue;
        } else chk(res);

        glfwPollEvents();
    }

    // vec_free(descriptor_set_writes);
    vkDeviceWaitIdle(program->device);

    vkDestroyShaderModule(program->device, shader, NULL);
    vkDestroyDescriptorPool(program->device, descriptor_pool, NULL);
    vkDestroyDescriptorSetLayout(program->device, descriptor_set_layout, NULL);
    vkDestroyPipelineLayout(program->device, pipeline_layout, NULL);
    vkDestroyPipeline(program->device, compute_pipeline, NULL);
}

void create_swapchain(Program* program) {
    VkSurfaceCapabilitiesKHR capabilities = get_capabilities(program);
    VkExtent2D image_size = capabilities.currentExtent;
    if (image_size.width == 0xFFFFFFFF) {
        int width = 0; int height = 0;
        glfwGetWindowSize(program->window, &width, &height);

        image_size.width = (u32)width;
        image_size.height = (u32)height;
    }

    program->image_format = image_size;

    VkSwapchainCreateInfoKHR create_info = {
        .sType          = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR,
        .surface        = program->surface, .minImageCount    = capabilities.minImageCount,
        .imageFormat    = IMAGE_FORMAT,     .imageColorSpace  = COLOR_SPACE,
        .imageExtent    = image_size,       .imageArrayLayers = 1,
        .imageUsage     = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_STORAGE_BIT,
        .preTransform   = VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR,
        .compositeAlpha = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR,
        .presentMode    = VK_PRESENT_MODE_FIFO_KHR,
    };

    chk(vkCreateSwapchainKHR(program->device, &create_info, NULL, &program->swapchain));

    u32 image_count = 0;
    chk(vkGetSwapchainImagesKHR(program->device, program->swapchain, &image_count, NULL));
    VkImage* images = NULL;
    vec_sized(images, image_count);
    chk(vkGetSwapchainImagesKHR(program->device, program->swapchain, &image_count, images));
    vec_len(images) = image_count;

    vec_free(program->images);
    program->images = images;

    VkSemaphore* semaphores = NULL;
    vec_sized(semaphores, image_count);

    VkSemaphoreCreateInfo sem_create_info = {
        .sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO
    };

    // Allocate all the new semaphores
    for (size_t i = 0; i < image_count; ++i) {
        vkCreateSemaphore(program->device, &sem_create_info, NULL, semaphores + i);
    }
    vec_len(semaphores) = image_count;

    // Destroy all the previous semaphores
    if (program->submit_semaphores != NULL)
    for (size_t i = 0; i < vec_len(program->submit_semaphores); ++i) {
        vkDestroySemaphore(program->device, program->submit_semaphores[i], NULL);
    }

    vec_free(program->submit_semaphores);
    program->submit_semaphores = semaphores;

    // TODO: Attach depth buffer
}

